require:
- rubocop-rails
- rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
Metrics/BlockLength:
  Max: 20
Style/Documentation:
  Enabled: false